# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20161228_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
